version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - config/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
volumes:
  pgdata:
    external: true

    


